### PR TITLE
US2-2 ADR Database Addition

### LINKED ISSUE #5: US 2-2 Database Selection
We have decided on using an external database to allow for live updates. Research and select a database to be used and create an ADR for this decision

### PR DESCRIPTION
**Pull request by dennisliang01**
We added the ADR document for the database selection.

### CODE REVIEW

**Review by chuongnguyen26 — APPROVED** [review]
Thanks for the ADR Specification, now I know why we chose to use local built in database.

**Comment by B3DAN** [comment]
Documentation update only

**Review by B3DAN — COMMENTED** [review]
Documentation Only

**Review by B3DAN — APPROVED** [review]

**Review by zhubzy — APPROVED** [review]
Looks good to me!

**Pull request merged**
